LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/teams?limit=200000"
  VENUE_ROOF: "https://en.wikipedia.org/wiki/List_of_current_Major_League_Baseball_stadiums"
  PLAYERS_ESPN: "https://sports.core.api.espn.com/v3/sports/baseball/mlb/athletes?limit=20000&active=true"
  ESPN_DETAILED: "https://site.api.espn.com/apis/common/v3/sports/baseball/mlb/athletes/{id}"
  TEAM_DETAILS:
    - "https://en.wikipedia.org/wiki/Arizona_Diamondbacks"
    - "https://en.wikipedia.org/wiki/Athletics_(baseball)"
    - "https://en.wikipedia.org/wiki/Atlanta_Braves"
    - "https://en.wikipedia.org/wiki/Baltimore_Orioles"
    - "https://en.wikipedia.org/wiki/Boston_Red_Sox"
    - "https://en.wikipedia.org/wiki/Chicago_Cubs"
    - "https://en.wikipedia.org/wiki/Chicago_White_Sox"
    - "https://en.wikipedia.org/wiki/Cincinnati_Reds"
    - "https://en.wikipedia.org/wiki/Cleveland_Guardians"
    - "https://en.wikipedia.org/wiki/Colorado_Rockies"
    - "https://en.wikipedia.org/wiki/Detroit_Tigers"
    - "https://en.wikipedia.org/wiki/Houston_Astros"
    - "https://en.wikipedia.org/wiki/Kansas_City_Royals"
    - "https://en.wikipedia.org/wiki/Los_Angeles_Angels"
    - "https://en.wikipedia.org/wiki/Los_Angeles_Dodgers"
    - "https://en.wikipedia.org/wiki/Miami_Marlins"
    - "https://en.wikipedia.org/wiki/Milwaukee_Brewers"
    - "https://en.wikipedia.org/wiki/Minnesota_Twins"
    - "https://en.wikipedia.org/wiki/New_York_Mets"
    - "https://en.wikipedia.org/wiki/New_York_Yankees"
    - "https://en.wikipedia.org/wiki/Philadelphia_Phillies"
    - "https://en.wikipedia.org/wiki/Pittsburgh_Pirates"
    - "https://en.wikipedia.org/wiki/San_Diego_Padres"
    - "https://en.wikipedia.org/wiki/San_Francisco_Giants"
    - "https://en.wikipedia.org/wiki/Seattle_Mariners"
    - "https://en.wikipedia.org/wiki/St_Louis_Cardinals"
    - "https://en.wikipedia.org/wiki/Tampa_Bay_Rays"
    - "https://en.wikipedia.org/wiki/Texas_Rangers_(baseball)"
    - "https://en.wikipedia.org/wiki/Toronto_Blue_Jays"
    - "https://en.wikipedia.org/wiki/Washington_Nationals"
  VENUES:
    - "https://en.wikipedia.org/wiki/American_Family_Field"
    - "https://en.wikipedia.org/wiki/Angel_Stadium"
    - "https://en.wikipedia.org/wiki/Busch_Stadium"
    - "https://en.wikipedia.org/wiki/Chase_Field"
    - "https://en.wikipedia.org/wiki/Citi_Field"
    - "https://en.wikipedia.org/wiki/Citizens_Bank_Park"
    - 'https://en.wikipedia.org/wiki/Comerica_Park'
    - "https://en.wikipedia.org/wiki/Coors_Field"
    - "https://en.wikipedia.org/wiki/Daikin_Park"
    - "https://en.wikipedia.org/wiki/Dodger_Stadium"
    - "https://en.wikipedia.org/wiki/Fenway_Park"
    - "https://en.wikipedia.org/wiki/George_M._Steinbrenner_Field"
    - "https://en.wikipedia.org/wiki/Globe_Life_Field"
    - "https://en.wikipedia.org/wiki/Great_American_Ball_Park"
    - "https://en.wikipedia.org/wiki/Kauffman_Stadium"
    - "https://en.wikipedia.org/wiki/LoanDepot_Park"
    - "https://en.wikipedia.org/wiki/Nationals_Park"
    - "https://en.wikipedia.org/wiki/Oracle_Park"
    - "https://en.wikipedia.org/wiki/Oriole_Park_at_Camden_Yards"
    - "https://en.wikipedia.org/wiki/Petco_Park"
    - "https://en.wikipedia.org/wiki/PNC_Park"
    - "https://en.wikipedia.org/wiki/Progressive_Field"
    - "https://en.wikipedia.org/wiki/Rate_Field"
    - "https://en.wikipedia.org/wiki/Rogers_Centre"
    - "https://en.wikipedia.org/wiki/Sutter_Health_Park"
    - "https://en.wikipedia.org/wiki/T-Mobile_Park"
    - "https://en.wikipedia.org/wiki/Target_Field"
    - "https://en.wikipedia.org/wiki/Truist_Park"
    - "https://en.wikipedia.org/wiki/Wrigley_Field"
    - "https://en.wikipedia.org/wiki/Yankee_Stadium"
ATTRIBUTES:
  TEAM_DETAILS:
    NAME: "//th[contains(@class, 'infobox-above') and contains(@class, 'fn')]/text()"
    ARENA: "//tr[th[contains(., 'Ballpark')]]/following-sibling::tr[1]/td//a | //tr[th[contains(., 'Ballpark')]]/td//a"
    COACH: "//th[@class='infobox-label'][contains(., 'Manager')]/following-sibling::td[1]"
    MANAGER: "//th[@class='infobox-label'][contains(., 'General manager')]/following-sibling::td[1]"
    CONFERENCE: "(//*[@id='mw-content-text']/div[1]/table[1]/tbody/tr[6]/td/div/ul/li/a[1] | //*[@id='mw-content-text']/div[1]/table[2]/tbody/tr[6]/td/div/ul/li/a[1])"
    DIVISION: "//div[contains(@style, 'text-align:left;')]//ul/li/ul/li/a[contains(text(), 'Division')]/text()"
  VENUES:
    NAME: "//table[contains(@class,'infobox')]//caption"
    CAPACITY: "//th[@class='infobox-label'][contains(., 'Capacity')]/following-sibling::td[1]"
    FIELD_SIZE_ALL: "//th[normalize-space(.)='Field size']/following-sibling::td//*[self::b or self::strong or self::span or self::small]/following-sibling::text()[not(ancestor::a or ancestor::sup)] | //th[normalize-space(.)='Field size']/following-sibling::td//small[not(ancestor::a or ancestor::sup)] | //th[normalize-space(.)='Field size']/following-sibling::td//br/following-sibling::text()[not(ancestor::a or ancestor::sup)]"
    SURFACE: "//th[@class='infobox-label'][contains(., 'Surface')]/following-sibling::td[1]"
    LATLON_DECIMAL: "//span[contains(@class, 'geo-dec')]/text()"
    WEBSITE: "//tr[th[contains(., 'Website')]]/following-sibling::tr[1]/td//a/@href"
